Move the mapper's BindKeys setup call to the early list
Previously the MAPPER_BindKeys's function was being inserted
into the init_functions' list via the AddInitFunction() call.

This was called inside the MAPPER_StartUp(), itself which is
being inserted via AddInitFunction() in sdlmain.

The nested call to AddInitFunction() invalides the
init_functions iterator when being called inside the
ExecuteInit loop, which is flagged as follows:

---

In function:
    _Safe_iterator<_Iterator, _Sequence, _Category> &
    gnu_debug::_Safe_iterator<std::
    _Deque_iterator<Section::Function_wrapper, Section::Function_wrapper &,
    Section::Function_wrapper *>, std::deque<Section::Function_wrapper>,
    std::forward_iterator_tag>::operator++() [_Iterator = std::
    _Deque_iterator<Section::Function_wrapper, Section::Function_wrapper &,
    Section::Function_wrapper *>, _Sequence =
    std::deque<Section::Function_wrapper>, _Category =
    std::forward_iterator_tag]

Error: attempt to increment a singular iterator.

Objects involved in the operation:
    iterator "this" @ 0x7ffd286f4118 {

      type = std::_Deque_iterator<Section::Function_wrapper,
      Section::Function_wrapper&, Section::Function_wrapper*> (mutable
      iterator);

 state = singular;

      references sequence with type
      'std::debug::deque<Section::Function_wrapper,
      std::allocator<Section::Function_wrapper> >' @ 0x55ffd476c400
    }

---

The fix is never to call AddInitFunction from
within a function already added via
AddInitFunction.