Run linters on Ubuntu 20.04, check ruby version
Fixes a workflow error:

 ERROR: Error installing mdl: The last version of chef-utils (>= 0) to
 support your Ruby & RubyGems was 16.6.14. Try installing it with `gem
 install chef-utils -v 16.6.14` and

 Then running the current command again chef-utils requires Ruby version
 >= 2.6.0. The current ruby version is 2.5.1.57.

Successfully installed rexml-3.2.4
Successfully installed kramdown-2.3.0
Successfully installed kramdown-parser-gfm-1.1.0
Successfully installed mixlib-cli-2.1.8
Successfully installed tomlrb-2.0.0
Successfully installed mixlib-config-3.0.9
Error: Process completed with exit code 1.