Implement save-states support
---

Notes from Ringding - (ported to 4467)

2021-10-21, 13:56 Fairly mechanical update of the mentioned patch to current
SVN. Only build-tested (on Linux). Specifically I did not check if additional
machine state items w ere added that would also require saving and restoring.

EDIT: Also pushed here because all this shuffling of huge subversion diffs is
really annoying:
https://github.com/Ringdingcoder/dosbox-staging/commits/savestates

---

Notes from bruenor41 - (ported to 4176)

2018-12-06, 04:27
I created patch file for sn 4176, hope correctly

In hardware.cpp I faced issue with variable std::string capturedir; Newly it
was defined as static which makes compilation errors in save_state.cpp :

save_state.o: In function `SaveState::save(unsigned int)':
save_state.cpp:(.text+0x7b4): undefined reference to `capturedir[abi:cxx11]'
save_state.cpp:(.text+0x7de): undefined reference to `capturedir[abi:cxx11]'
save_state.o: In function `SaveState::load(unsigned int) const':
save_state.cpp:(.text+0x165a): undefined reference to `capturedir[abi:cxx11]'
save_state.cpp:(.text+0x1684): undefined reference to `capturedir[abi:cxx11]'
collect2: error: ld returned 1 exit status

changing it back to non static solved the error, how it should be fixed
correctly ?

---

Notes from SedrynTyros - (ported to 4074)

2018-10-19, 07:46
Oh yeah, definitely still interested in having a save states patch compatible
with current DOSBox builds! I have a feeling the DOSBox devs are done with
making major changes to the code pending the upcoming 0.75 release, so if you
or bruenor can figure out how to modify the save state code to be compatible
with the Gameblaster and Tandy changes and produce a patch we're probably be
good to go for the foreseeable future. And thanks again for all the work you
guys have done on this!

I was able to clean up the r4019 patch to work with r4074. I'll do some more
testing to see if it actually works with games, but initial results look good.
If I can find the time to confirm it works I'll upload the patch here.

I've attached the modified patch that applies cleanly to DOSBox r4074 named
"bruenor41_savestate_r4074_win32_mingw_v2_st-update.patch". The patch is based
on "bruenor41_savestate_r4019_win32_mingw.patch" but also includes the fix for
raiden that bruenor41 posted here:

I've tested a few games and Save States seem to work correctly. I don't really
have time for extensive testing right now, but I've attached
"DOSBox-SVN-r4074-with-Save-States.rar" which is the basic DOSBox build I
compiled for testing if somebody else wants to play around with it.

---

Notes from bruenor41 - (fixes to 4019 patch)

2017-09-07, 00:49
Hi, I updated save states, some things were not saved, so I took missing stuff
from daum build and I fixed some errors by myself, I don't understand why these
errors didn't appear in daum... I use more enhanced version, so I merged
changes to r4019, hope without errors. Sorry, I don't know how to create diff.
With these changes increases significantly range of games which supports
save/load states, but still not perfect. Dynrec needs more mork, it wont load
everything correctly. Seems, it needs reset, like has _x86 version.

Fixes:
  C&C1 and Red Alert - fixed segmentation faults
  Fallout 1 - fixed crash when loading states through different areas
  Earth 2140 - fixed crash
  Wolfenstein 3d + SWOLF - fixes graphical glitches
  Lands of Lore 1 - loads now correctly when loading through different areas,
  dynrec does not work here

Games what I tested for a longer time and seems to be OK:
  Warcraft 1,2
  Albion - from beginning to the end I used states and works at 100%
  Fallout 1
  C&C1
  Doom
  Might and Magic 1
  KKND
  Ignition
  Wacky wheels
  Dangerous Dave
  Bio Menace

Shortly tested:
  Settlers 2
  Realms of Arkania 1,2 (3rd part was not tested)
  Monkey Island 1
  Ultima 7 - states wont load during intro and menu, but in game it works
  Duke 3D
  Syndicate
  Willy Beamish

Games which I cant get work:
  Daggerfall

2017-09-17, 23:26
Hi people, here is newest version of save/load states. Because my knowledge of
cpu is not so good, I asked M-HT for a help. He implemented missing dynrec
cache reset. I send him big thanks. I merged that fix to version posted above.
As far as I tried, all games tested by me were loaded correctly now. Please, if
you find game what does not work correctly with save/load states, post here
it's name and your dosbox configuration. I'll try look at this.

EDIT : Save states checks which exe file is currently loaded. Might happen that
you try load save stated during intro, but intro might be another exe file
loaded by main game file. In this case, states are loaded when intro finishes
and is loaded correct exe file.

2017-10-03, 04:21
I fixed most critical issue when loading states in Alien Carnage. Another rare
situation must wait, but seems it is far enough for this game, it works well.

Edit : uploaded sources with latest fix
Please report game which wont work with states

---

Notes from gandhig - (ported patch to r3782 through r4019)

Thanks to ZenJu, tikalat, ykhwong and of course, all the dosbox authors, here
is an alpha version of Dosbox SVN r4019 with savestates(patches taken from this
thread), built statically(with few shared dependencies) for debian 32 bit linux
systems(tested on lubuntu only) as well as for windows.

Purists & old-timers(including myself) may please forgive.

Summary:

  1) diff uploaded by tikalat against Dosbox SVN 3782(patch-005) was used as a
     base.

  2) Added/removed certain data/data structs/POD's by comparing them between
     r3782 and r4007. Adapted to r4019 later without further changes.

  3) Under Dos Files, "LPT1" was needed in addition to "CON", "PRN" & "AUX"
     checks. Probably it was fixed by tikalat in his later patches to daum
     build.

  4) Save/Load to/from Disk code copied from latest Daum build.

  5) Aim is to reach the savestates compatibility level of tikalat's 'savestate
     patch 005' to SVN r3782 build

Tested games (i.e. no regular crash 🤣):
  a) Lure of the Temptress
  b) XCOM UFO Defense
  c) Turrican II
  d) GP2 99 by Microprose
  e) Wacky wheels (Thanks to bruenor41)
  f) Dangerous dave 2 in the haunted mansion (Thanks to bruenor41)
  g) Fallout 1 (Thanks to bruenor41)
  h) Bio Menace (Thanks to bruenor41)
  i) Might & Magic 1 (Thanks to bruenor41)

Issues/Fix needed/To Do:

  a) GP2 throws segmentation fault just after loading the saves. Issue was not
     observed in the buid of SVN 3782(with tikalat's savestate-005 patch
     applied). Got fixed automatically in SVN r4019.

  b) May not work with Dune as 'opl3gold' mode not added yet. Not sure if it is
     required or that it will crash, as Dune is not available with me.

  c) There maybe code regression due to certain new or replaced data/POD's in
     r4019 w.r.t r3782.

  d) Compile win32 build - Completed.

  e) Add MUNT support - Dropped

  f) etc.

Note:
  1) Intentionally no code was added 🤣 to the main SVN source.
  2) Dosbox SVN source/diff added in posts below
  3) Those who download the build are requested to run it first in a virtual
     environment, if possible, to avoid hard crashes.

Shortcut Keys:

Left ALT + F5 -> Save to current slot
Left ALT + F9 -> Load state from current slot
Left ALT + F6 -> Switch to previous slot
Left ALT + F7 -> Switch to next slot

Total saveslots : 10 (Slots in circular arrangement)

Imported-from: https://www.vogons.org/viewtopic.php?p=1011662#p1011662

Authors listed from old/original to new:
  ZenJu & tikalat - primary authors
  ykhwong - ported into Daum
  gandhig - ported to r3782 to r4019
  bruenor41 - fixes to r4019 ported to
  Stefan Ring (Ringdingcoder) - ported to 4467

Co-authored-by: ZenJu <ZenJu@vogons.org>
Co-authored-by: tikalat <tikalat@vogons.org>
Co-authored-by: ykhwong <ykhwong@daum.net>
Co-authored-by: gandhig <gandhig@vogons.org>
Co-authored-by: bruenor41 <bruenor41@vogons.org>
Co-authored-by: SedrynTyros <SedrynTyros@vogons.org>
Co-authored-by: Stefan Ring <stefanrin@gmail.com>