Check the usability of Apple's audio headers in Meson
Also add ObjectiveC parsing on macOS if possible.

Apple sometimes pollutes their headers with non-standard content
that only compiles using their modified compiler.

Because of this, simply testing for the presence of the CoreMIDI
header is insufficient; instead, we need to make sure the compiler
can actually process it.

This will protect GCC from errors like this:

/libmidi.a.p/midi.cpp.o -MF src/midi/libmidi.a.p/midi.cpp.o.d -o
src/midi/libmidi.a.p/midi.cpp.o -c ../src/midi/midi.cpp In file included
from ../src/midi/midi_coremidi.h:29,
                 from ../src/midi/midi.cpp:84:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:304:2:
error: expected unqualified-id before '^' token
  304 | (^MIDINotifyBlock)(const MIDINotification *message);
      |  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:304:2:
  error: expected ')' before '^' token 304 | (^MIDINotifyBlock)(const
  MIDINotification *message);
      | ~^ )
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:347:2:
  error: expected unqualified-id before '^' token 347 |
  (^MIDIReadBlock)(const MIDIPacketList *pktlist, void * __nullable
  srcConnRefCon);
      |  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:347:2:
  error: expected ')' before '^' token 347 | (^MIDIReadBlock)(const
  MIDIPacketList *pktlist, void * __nullable srcConnRefCon);
      | ~^ )
In file included from ../src/midi/midi_coremidi.h:29, from
                 ../src/midi/midi.cpp:84:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1190:41:
 error: 'MIDINotifyBlock' has not been declared 1190 | MIDINotifyBlock
 __nullable notifyBlock ) API_AVAILABLE(macos(10.11), ios(9.0),
 tvos(12.0));