Rename the OUT lambda to fix a naming conflict
Fixes:

     (ClCompile target) ->
         D:\a\dosbox-staging\dosbox-staging\src\hardware\vga_draw.cpp(113,11):
         error C2513: 'auto': no variable declared before '='
         [D:\a\dosbox-staging\dosbox-staging\vs\dosbox.vcxproj]